### ISSUE TITLE
undefined refrences

### ISSUE THREAD

**Issue by vincenzoiovino** [jedisct1/openssl-wasm#3]
Hello,
I try to compile a program with emcc linking your libcrypto.a and I get the following errors:

![image](https://github.com/jedisct1/openssl-wasm/assets/41876613/2bf728fe-ef78-4290-921f-21a39ce1b09a)

Any clue on how to fix it?

**Comment by jedisct1** [comment]
There are multiple incompatible environments for WebAssembly.

This build is for WebAssembly with in a WASI environment (`wasm32-wasi`). It's supported by Node, Bun, and dedicated runtimes such as Wasmedge. But not by web browsers without an additional module (such as [`wasmerjs`](https://www.npmjs.com/package/@wasmer/wasi)).

Emscripten is a different environment (`wasm32-emscripten`), with an incompatible API.

If you want to compile C code to WASI, you need to use the `zig cc` compiler instead of `emcc`.
